intro_to_rails_homework/config/routes.rb
Rails.application.routes.draw do


  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

intro_to_rails_homework/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

intro_to_rails_homework/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

intro_to_rails_homework/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

intro_to_rails_homework/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

intro_to_rails_homework/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "brad", password:'1234', only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find (params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destory
    redirect_to post_path(@post)

  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end



end

intro_to_rails_homework/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "brad", password:'1234', except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

    @post = Post.find(params[:id])

    # if (@post.update(post_params))
    #   redirect_to @post
    # else
    #   render 'edit'
    # end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

intro_to_rails_homework/app/helpers/application_helper.rb
module ApplicationHelper
end

intro_to_rails_homework/app/helpers/comments_helper.rb
module CommentsHelper
end

intro_to_rails_homework/app/helpers/posts_helper.rb
module PostsHelper
end

intro_to_rails_homework/app/views/comments/_comments.html.erb
<h3>Comments</h3>

<% @post.comments.each do |comment| %>
<div class="well">
  <p><strong><%= comment.username %></strong>: <%= comment.body %>
    <%= link_to '[X]', [comment.post, comment], method: :delete, data: {confirm: 'are you sure?'} %>
  </p>
</div>
<% end %>

intro_to_rails_homework/app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :username %> <br>
    <%= f.text-field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :body %> <br>
    <%= f.text-area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit(:class => 'btn btn-default') %>
  </p>
  <% end %>

intro_to_rails_homework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRailsHomework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
     <a class="navbar-brand" href="#">Navbar</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarsExampleDefault">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
           <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#">Link</a>
         </li>
         <li class="nav-item">
           <%= link_to "Home", home_path %>
         </li>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
           <div class="dropdown-menu" aria-labelledby="dropdown01">
             <a class="dropdown-item" href="#">Action</a>
             <a class="dropdown-item" href="#">Another action</a>
             <a class="dropdown-item" href="#">SimpleBlog</a>
           </div>
         </li>
       </ul>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Create Post", new_post_path %></li>
       </ul>
       <form class="form-inline my-2 my-lg-0">
         <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
       </form>
     </div>
   </nav>

   <div class="container">

     <%= yield %>
   </div>
  </body>
</html>

intro_to_rails_homework/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

intro_to_rails_homework/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>


<h1>Edit Post</h1>

<%= form_for :post, url: posts_path(@post), method: :patch do |f| %>

<% if @post.errors.any? %>
<% @post.errors_full_messages.each do |msg| %>
<div class="alert alert-danger"> <%= msg %></div>
<% end %>
<% end %>


<p>
  <%= f.label :title %> <br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>

</p>

<p>
  <%= f.label :body %><br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
  <%= f.submit({:class => 'btn, btn-primary'}) %>
</p>

<% end %>

intro_to_rails_homework/app/views/posts/index.html.erb
<h1>Blog Post</h1>
  <% @posts.each do |post| %>
  <div class="well">
    <h3> <%= post.title %> </h3>
    <p> <%= post.body %></p>
    <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
  </div>
  <% end %>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

intro_to_rails_homework/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>


<h1>Add Post</h1>

<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>
<% @post.errors_full_messages.each do |msg| %>
<div class="alert alert-danger"> <%= msg %></div>
<% end %>
<% end %>


<p>
  <%= f.label :title %> <br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>

</p>

<p>
  <%= f.label :body %><br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
  <%= f.submit({:class => 'btn, btn-primary'}) %>
</p>

<% end %>

intro_to_rails_homework/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Title:</strong>
  <%= @post.title %>
</h2>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<hr>


<%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-default' %> |
<%= link_to 'Delete', posts_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
<hr>


<%= render 'comments/comments'%>
<%= render 'comments/form'%>